### ISSUE TITLE
fogg.json as suggeted does not work

### ISSUE THREAD

**Issue by queglay** [chanzuckerberg/cztack#439]
I wasn't able to get the provider working by just defining it in terraform, so I tried the suggested workflow with fogg in an empty repo:
```
user@MacBook-Pro bless-test % fogg apply                                 
fogg.yml has error(s):
ERROR: could not open fogg.yml config file
user@MacBook-Pro bless-test % fogg version
0.76.0
```

The docs suggested I use these contents for fogg.json:
```
{
  "defaults":{},
  "modules":{},
  "accounts":{},
  "envs":{},
  "plugins": {
    "terraform_providers": {
      "terraform-provider-bless": {
        "url": "https://github.com/chanzuckerberg/terraform-provider-bless/releases/download/v0.2.5/terraform-provider-bless_0.2.5_linux_amd64.tar.gz",
        "format": "tar"
      }
    }
  }
}
```

I'm guessing v0.76 requires a yaml and not json anymore, so I tried converting the suggested json to fogg.yaml:
```
defaults: {}
modules: {}
accounts: {}
envs: {}
plugins:
    terraform_providers:
        terraform-provider-bless:
            url: 'https://github.com/chanzuckerberg/terraform-provider-bless/releases/download/v0.2.5/terraform-provider-bless_0.2.5_linux_amd64.tar.gz'
            format: tar
```
This also produced errors, so I'm guessing the specified information is not sufficient to get started.
```
user@MacBook-Pro bless-test % fogg apply    
fogg.yml has error(s):
UNKNOWN ERROR: 4 errors occurred:
        * Key: 'Config.Version' Error:Field validation for 'Version' failed on the 'required' tag
        * global must have a valid owner set at either the global or defaults level
        * global must have a valid project set at either the global or defaults level
        * global must have a valid terraform version set at either the global or defaults level
```
